#define ALT_J  LALT_T(KC_J)
#define CTL_A  LCTL_T(KC_A)
#define CTL_S  LCTL_T(KC_S)
#define ENT_Z  TD(TD_ENT_Z)
#define F1_SPC LT(1, KC_SPC)
#define F2_K   LT(2, KC_K)
#define F3_M   LT(3, KC_M)
#define GUI_Q  LGUI_T(KC_Q)
#define KC_LCA LCA_T(KC_NO)
#define SFT_X  LSFT_T(KC_X)
