#define	 ALT_J	 LALT_T(KC_J)
#define	 ALT_X	 LALT_T(KC_X)
#define	 CTL_A	 LCTL_T(KC_A)
#define	 CTL_S	 LCTL_T(KC_S)
#define	 ENT_Z   TD(TD_ENT_Z)
#define	 F1_SPC	 LT(_LOWER, KC_SPC)
#define	 F2_C	 LT(_RAISE, KC_C)
#define	 F2_X	 LT(_RAISE, KC_X)
#define	 F2_V	 LT(_RAISE, KC_V)
#define	 GUI_Q	 LGUI_T(KC_Q)
#define	 KC_LCA	 LCA_T(KC_NO)
#define	 SFT_X	 LSFT_T(KC_X)
#define	 ENT_DOT TD(TD_ENT_DOT)
