AUDIO_ENABLE     = no        # Audio output on port C6
BACKLIGHT_ENABLE = no        # Enable keyboard backlighting
BOOTLOADER       = atmel-dfu # Elite-C
BOOTMAGIC_ENABLE = yes       # Enable bootmagic Lite
CONSOLE_ENABLE   = no        # QMK Console for debug
COMMAND_ENABLE   = no        # Commands for debug and configuration
EXTRAKEY_ENABLE  = yes       # Audio control and system control
LTO_ENABLE       = no        # improve performance/size
MIDI_ENABLE      = no        # MIDI support
NKRO_ENABLE      = no        # USB Nkey rollover
RGBLIGHT_ENABLE  = no        # Enable RGB underlighting
TAP_DANCE_ENABLE = yes       # Enable tap-dance
UNICODE_ENABLE   = no        # Unicode char support
VIA_ENABLE       = no        # configure keyboard via usevia.app
